name: flutter_initializer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_jailbreak_detection:
    git:
      url: https://github.com/pdurasie-ecovery/flutter_jailbreak_detection.git
      ref: add-namespace

  flutter_riverpod: ^2.6.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  easy_localization: ^3.0.7+1
  auto_route: ^10.0.1
  local_auth: ^2.3.0
  location: ^8.0.0
  url_launcher: ^6.3.1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
